pipeline {
    agent {docker 'didstopia/msbuild'}
    environment {
        BRANCH = ""
    }
    stages {
        stage('Preparing the job') {
            steps {
                script {
                    properties(
                        [parameters([choice(choices: ["Debug", "Release"].join("\n"),
                        description: 'Configuration for the build', 
                        name: 'Configuration')])])
                }
            }
        }
        stage('Pull latest commit') {
            steps {
                script {
                    if (params.Configuration == 'Release') {
                        BRANCH = 'master'
                    } else
                    {
                        BRANCH = 'dev'
                    }
                }
                echo "Branch is ${BRANCH}"

                git branch: BRANCH, url: 'https://github.com/daftkid/disk_cleaner.git'
            }
        }
        stage('Build') {
            steps {
                sh "msbuild.exe *.sln /p:Configuration=${params.Configuration}"
                archiveArtifacts artifacts: "bin/${params.Configuration}/*.exe", fingerprint: true
            }
        }
    }
}
